[".local/share/oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/swaync/style.css"]
    type = "file"
    url = "https://raw.githubusercontent.com/ErikReider/Linux/master/dotfiles/swayConfig/swaync/style.css"
    refreshPeriod = "168h"
